language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=3.1"
  - "RAILS_VERSION=3.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - rvm: 2.0.0
    - env: "RAILS_VERSION=master"
    - env: "RAILS_VERSION=3.0"
    - env: "RAILS_VERSION=3.1"
  exclude:
    - rvm: 2.0.0
      env: "RAILS_VERSION=3.0"
    - rvm: 2.0.0
      env: "RAILS_VERSION=3.1"
    - rvm: 1.8.7
      env: "RAILS_VERSION=master"
    - rvm: 1.9.2
      env: "RAILS_VERSION=master"

